// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as CollapsibleProps } from '@zag-js/collapsible';

export type CollapsibleHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<CollapsibleProps, 'defaultOpen'> &
    Partial<Pick<CollapsibleProps, 'disabled' | 'collapsedHeight' | 'collapsedWidth'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        collapsible: CollapsibleHydrationProps;
    }
}
