// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as RadioGroupProps } from '@zag-js/radio-group';

export type RadioGroupHydrationProps = {
id: string,
ids: Record<string, string>,
} & Pick<RadioGroupProps, 'orientation'> & Partial<Pick<RadioGroupProps, 'defaultValue' | 'name' | 'form' | 'disabled' | 'readOnly' | 'required' | 'invalid'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        radioGroup: RadioGroupHydrationProps;
    }
}
