// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
export type ScrollAreaHydrationProps =
    { id: string; ids: Record<string, string> };

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        scrollArea: ScrollAreaHydrationProps;
    }
}
