// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as CheckboxProps } from '@zag-js/checkbox';

export type CheckboxHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<CheckboxProps, 'defaultChecked' | 'value'> &
    Partial<Pick<CheckboxProps, 'disabled' | 'invalid' | 'required' | 'name' | 'form' | 'readOnly'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        checkbox: CheckboxHydrationProps;
    }
}
