// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as TabsProps } from '@zag-js/tabs';

export type TabsHydrationProps = { id: string; ids: Record<string, string> } & Pick<
    TabsProps,
    'loopFocus' | 'orientation' | 'activationMode' | 'composite'
> &
    Partial<Pick<TabsProps, 'defaultValue' | 'deselectable'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        tabs: TabsHydrationProps;
    }
}
