// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as MenuProps } from '@zag-js/menu';

export type MenuHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<MenuProps, 'closeOnSelect' | 'composite' | 'typeahead' | 'loopFocus' | 'positioning' | 'defaultOpen'> &
    Partial<Pick<MenuProps, 'defaultHighlightedValue' | 'defaultTriggerValue'>> &
    { ariaLabel?: string; parentId?: string };

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        menu: MenuHydrationProps;
    }
}
