// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as PopoverProps } from '@zag-js/popover';

export type PopoverHydrationProps = { id: string; ids: Record<string, string> } & Pick<
    PopoverProps,
    | 'modal'
    | 'portalled'
    | 'autoFocus'
    | 'restoreFocus'
    | 'closeOnInteractOutside'
    | 'closeOnEscape'
    | 'defaultOpen'
    | 'translations'
> &
    Partial<Pick<PopoverProps, 'positioning'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        popover: PopoverHydrationProps;
    }
}
