// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
export type ListCollectionData = {
items: any[],
size: number,
first: string | null,
last: string | null,
itemToValueKey: string | null,
itemToStringKey: string | null,
isItemDisabledKey: string | null,
groupByKey: string | null,
groupSort: 'asc' | 'desc' | string[] | null,
};
