// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { FieldArrayProps } from './src/field-array.types';

export type FieldArrayHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<FieldArrayProps, 'name' | 'itemCount' | 'translations'> &
    Partial<Pick<FieldArrayProps, 'minItems' | 'maxItems'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        fieldArray: FieldArrayHydrationProps;
    }
}
