// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as SwitchProps } from '@zag-js/switch';

export type SwitchHydrationProps = { id: string; ids: Record<string, string> } & Pick<
    SwitchProps,
    'defaultChecked' | 'value'
> &
    Partial<Pick<SwitchProps, 'disabled' | 'invalid' | 'required' | 'name' | 'form' | 'readOnly'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        switch: SwitchHydrationProps;
    }
}
