<?php

declare(strict_types=1);

namespace Jramke\FluidPrimitives\Command;

/**
 * Renders a primitive's generated `<Name>.hydration.ts` file content and idempotently ensures its
 * own `<Name>.ts` re-exports the generated type - required so `tsdown`'s per-primitive flat dist
 * entry (`tsdown.config.ts`, one entry per primitive) actually reaches it; a standalone,
 * never-imported-from-`<Name>.ts` file wouldn't reach `dist/<name>.d.ts` at all. Output is plain,
 * reasonably-formatted TS - {@see PrettierFormatter} runs this class's own output through the
 * monorepo's real Prettier config before `GenerateHydrationTypesCommand` writes or diffs it,
 * rather than this class hand-matching `.prettierrc` exactly.
 */
final class HydrationFileWriter
{
    private const string HEADER = "// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.\n";

    /**
     * @param list<HydrationPropDefinition> $propDefinitions
     */
    public function buildFileContent(
        string $primitiveName,
        string $clientComponentName,
        array $propDefinitions,
        ?HydrationPropsTypeSource $propsSource,
    ): string {
        $typeName = $primitiveName . 'HydrationProps';

        $requiredPickKeys = [];
        $optionalPickKeys = [];
        $requiredLiteralFields = [];
        $optionalLiteralFields = [];
        $imports = [];

        foreach ($propDefinitions as $definition) {
            if ($definition->pickFromPropsType) {
                if (!$definition->required) {
                    $optionalPickKeys[] = $definition->name;
                    continue;
                }
                $requiredPickKeys[] = $definition->name;
                continue;
            }

            if ($definition->tsImport !== null) {
                $imports[$definition->tsImport] = true;
            }

            if (!$definition->required) {
                $optionalLiteralFields[] = sprintf('%s?: %s', $definition->name, $definition->tsType);
                continue;
            }
            $requiredLiteralFields[] = sprintf('%s: %s', $definition->name, $definition->tsType);
        }

        $typeParts = ['{ id: string; ids: Record<string, string> }'];

        if ($requiredPickKeys !== [] && $propsSource !== null) {
            $imports[$propsSource->tsImport] = true;
            $typeParts[] = sprintf('Pick<%s, %s>', $propsSource->typeName, $this->quotedUnion($requiredPickKeys));
        }
        if ($optionalPickKeys !== [] && $propsSource !== null) {
            $imports[$propsSource->tsImport] = true;
            $typeParts[] = sprintf(
                'Partial<Pick<%s, %s>>',
                $propsSource->typeName,
                $this->quotedUnion($optionalPickKeys),
            );
        }
        if ($requiredLiteralFields !== []) {
            $typeParts[] = sprintf('{ %s }', implode('; ', $requiredLiteralFields));
        }
        if ($optionalLiteralFields !== []) {
            $typeParts[] = sprintf('{ %s }', implode('; ', $optionalLiteralFields));
        }

        $importLines = array_keys($imports);
        sort($importLines);

        $lines = [self::HEADER];
        if ($importLines !== []) {
            $lines[] = implode("\n", $importLines) . "\n\n";
        }

        $lines[] = sprintf("export type %s =\n    %s;\n\n", $typeName, implode(" &\n    ", $typeParts));
        $lines[] = sprintf(
            "declare module 'fluid-primitives/client' {\n    interface HydrationPropsRegistry {\n        %s: %s;\n    }\n}\n",
            $clientComponentName,
            $typeName,
        );

        return implode('', $lines);
    }

    /**
     * Appends `export type { <Name>HydrationProps } from './<Name>.hydration';` right after
     * `<Name>.ts`'s own last top-level `import` statement, if not already present - a no-op on a
     * re-run once the line exists.
     */
    public function ensureReExport(string $classFilePath, string $primitiveName): void
    {
        $content = (string)file_get_contents($classFilePath);
        $exportLine = sprintf(
            "export type { %sHydrationProps } from './%s.hydration';",
            $primitiveName,
            $primitiveName,
        );

        if (str_contains($content, $exportLine)) {
            return;
        }

        $lines = explode("\n", $content);
        $lastImportIndex = null;
        foreach ($lines as $index => $line) {
            if (!str_starts_with($line, 'import ')) {
                continue;
            }

            $lastImportIndex = $index;
        }

        if ($lastImportIndex === null) {
            // No imports at all is not a shape any current primitive's <Name>.ts has, but fail
            // safely rather than corrupt the file if a future one ever doesn't.
            throw new \RuntimeException(
                sprintf('Cannot find an import statement to anchor the generated re-export in "%s".', $classFilePath),
                1_788_400_003,
            );
        }

        array_splice($lines, $lastImportIndex + 1, length: 0, replacement: [$exportLine]);
        file_put_contents($classFilePath, implode("\n", $lines));
    }

    /**
     * @param list<string> $keys
     */
    private function quotedUnion(array $keys): string
    {
        return implode(' | ', array_map(static fn(string $key): string => "'" . $key . "'", $keys));
    }
}
