<?php

declare(strict_types=1);

namespace Jramke\FluidPrimitives\Command;

use Spatie\TypeScriptTransformer\Actions\ResolveImportsAndResolvedReferenceMapAction;
use Spatie\TypeScriptTransformer\Collections\TransformedCollection;
use Spatie\TypeScriptTransformer\Data\GlobalNamespaceResolvedReference;
use Spatie\TypeScriptTransformer\Data\ModuleImportResolvedReference;
use Spatie\TypeScriptTransformer\Data\WriteableFile;
use Spatie\TypeScriptTransformer\Data\WritingContext;
use Spatie\TypeScriptTransformer\Transformed\Transformed;
use Spatie\TypeScriptTransformer\TypeScriptNodes\TypeScriptImport;
use Spatie\TypeScriptTransformer\Writers\Writer;

/**
 * A {@see Writer} that writes every `Transformed` routed to one instance into a single file at a
 * fixed, caller-chosen `$path` (an absolute filesystem path - this class never consults
 * `TypeScriptTransformerConfig::$outputDirectory`, {@see GenerateHydrationTypesCommand} writes files
 * itself instead of going through spatie's own `WriteFilesAction`, so `--output` can point anywhere
 * on disk, not just somewhere under one common root) - the same shape as spatie's own
 * `FlatModuleWriter`, plus this codegen's own AUTO-GENERATED header/optional footer and an
 * `import type` rewrite (`TypeScriptImport` always emits a plain `import { ... }`, which fails this
 * repo's `verbatimModuleSyntax` tsconfig for a type-only import).
 *
 * `GenerateHydrationTypesCommand` uses one shared instance (its config's default `typesWriter`, for
 * every `#[TypeScript]` shape class under `Classes/Domain/Dto/`) plus one instance per component
 * ({@see HydrationTransformedProvider}, each carrying its own `<Name>.hydration.ts` path via
 * `Transformed::setWriter()`). `ResolveFilesAction`/
 * `Collections\TransformedCollection::ensureEachTransformedHasAWriter()` group `Transformed`s by
 * writer *instance*, which is what actually gives every primitive its own exactly-named file - the
 * stock `ModuleWriter`'s fixed-`moduleFilename`-per-location-directory model can't do that; its own
 * docs example writes `index.ts`/`index.d.ts`, not an arbitrary per-type filename.
 */
final class HydrationTypeScriptWriter implements Writer
{
    private const string HEADER = "// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.\n";

    private readonly ResolveImportsAndResolvedReferenceMapAction $resolveImports;

    public function __construct(
        private readonly string $path,
        private readonly string $footer = '',
        /** The one external (non-`#[TypeScript]`-tracked) `import type { ... }` line this file's own `Pick<>` source needs, e.g. a Zag package's `Props` - spatie has no visibility into an npm package's own `.d.ts`, so this stays a hand-carried raw string rather than a real reference. */
        private readonly ?string $rawImport = null,
        ResolveImportsAndResolvedReferenceMapAction $resolveImports = new ResolveImportsAndResolvedReferenceMapAction(),
    ) {
        $this->resolveImports = $resolveImports;
    }

    public function output(array $transformed, TransformedCollection $transformedCollection): array
    {
        [$imports, $resolvedReferenceMap] = $this->resolveImports->execute(
            $this->path,
            $transformed,
            $transformedCollection,
        );

        $writingContext = new WritingContext($resolvedReferenceMap);

        $importLines = array_map(static fn(TypeScriptImport $import): string => str_replace(
            search: 'import {',
            replace: 'import type {',
            subject: $import->write($writingContext),
        ), $imports->getTypeScriptNodes());
        if ($this->rawImport !== null) {
            $importLines[] = $this->rawImport;
        }
        sort($importLines);

        $output = self::HEADER;
        if ($importLines !== []) {
            $output .= implode("\n", $importLines) . "\n\n";
        }

        usort(
            $transformed,
            static fn(Transformed $a, Transformed $b) => ($a->getName() ?? '') <=> ($b->getName() ?? ''),
        );
        foreach ($transformed as $item) {
            $output .= $item->write($writingContext) . "\n";
        }

        if ($this->footer !== '') {
            $output .= "\n" . $this->footer;
        }

        return [new WriteableFile($this->path, $output)];
    }

    public function resolveReference(Transformed $transformed): ModuleImportResolvedReference|GlobalNamespaceResolvedReference
    {
        $name = $transformed->getName() ?? throw new \LogicException(sprintf(
            'Transformed at "%s" has no name to reference it by.',
            $this->path,
        ));

        return new ModuleImportResolvedReference($name, $this->path);
    }
}
