// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { FieldProps } from './src/field.types';

export type FieldHydrationProps = { id: string; ids: Record<string, string> } & Pick<
    FieldProps,
    'name'
> &
    Partial<
        Pick<
            FieldProps,
            'disabled' | 'invalid' | 'required' | 'readOnly' | 'defaultValue' | 'listenTo'
        >
    >;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        field: FieldHydrationProps;
    }
}
