// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { InputProps } from './src/input.types';

export type InputHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<InputProps, 'defaultValue' | 'translations' | 'announceDebounce'> &
    Partial<Pick<InputProps, 'name' | 'disabled' | 'invalid' | 'required' | 'readOnly' | 'maxLength' | 'pattern' | 'inputMode'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        input: InputHydrationProps;
    }
}
