// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { ListCollectionData } from '../../Client/src/types.generated';
import type { Props as SelectProps } from '@zag-js/select';

export type SelectHydrationProps = {
id: string,
ids: Record<string, string>,
} & Pick<SelectProps, 'closeOnSelect' | 'positioning' | 'loopFocus' | 'defaultOpen' | 'composite' | 'translations'> & Partial<Pick<SelectProps, 'name' | 'form' | 'disabled' | 'invalid' | 'readOnly' | 'required' | 'defaultValue' | 'defaultHighlightedValue' | 'multiple' | 'deselectable'>> & {
collection: ListCollectionData,
};

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        select: SelectHydrationProps;
    }
}
