// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { ListCollectionData } from 'fluid-primitives/client';
import type { Props as ComboboxProps } from '@zag-js/combobox';

export type ComboboxHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<ComboboxProps, 'defaultOpen' | 'openOnClick' | 'openOnKeyPress' | 'openOnChange' | 'loopFocus' | 'allowCustomValue' | 'alwaysSubmitOnEnter' | 'inputBehavior' | 'composite' | 'positioning' | 'translations'> &
    Partial<Pick<ComboboxProps, 'name' | 'form' | 'disabled' | 'invalid' | 'readOnly' | 'required' | 'placeholder' | 'defaultValue' | 'defaultInputValue' | 'defaultHighlightedValue' | 'closeOnSelect' | 'multiple' | 'selectionBehavior' | 'autoFocus' | 'searchUrl'>> &
    { collection: ListCollectionData };

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        combobox: ComboboxHydrationProps;
    }
}
