// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as SliderProps } from '@zag-js/slider';

export type SliderHydrationProps = {
id: string,
ids: Record<string, string>,
} & Pick<SliderProps, 'min' | 'max' | 'step' | 'minStepsBetweenThumbs' | 'orientation' | 'origin' | 'thumbAlignment' | 'thumbCollisionBehavior'> & Partial<Pick<SliderProps, 'disabled' | 'readOnly' | 'invalid' | 'name' | 'form' | 'defaultValue' | 'largeStep' | 'thumbSize'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        slider: SliderHydrationProps;
    }
}
