// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as NavigationMenuProps } from '@zag-js/navigation-menu';

export type NavigationMenuHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<NavigationMenuProps, 'orientation' | 'defaultValue' | 'openDelay' | 'closeDelay'> &
    Partial<Pick<NavigationMenuProps, 'disableHoverTrigger' | 'disableClickTrigger' | 'disablePointerLeaveClose'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        navigationMenu: NavigationMenuHydrationProps;
    }
}
