// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { CheckboxGroupProps } from './src/checkbox-group.types';

export type CheckboxGroupHydrationProps =
    { id: string; ids: Record<string, string> } &
    Partial<Pick<CheckboxGroupProps, 'defaultValue' | 'name' | 'form' | 'disabled' | 'readOnly' | 'required' | 'invalid' | 'maxSelectedValues'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        checkboxGroup: CheckboxGroupHydrationProps;
    }
}
