// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as TooltipProps } from '@zag-js/tooltip';

export type TooltipHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<TooltipProps, 'defaultOpen' | 'disabled' | 'openDelay' | 'closeDelay' | 'closeOnPointerDown' | 'closeOnEscape' | 'closeOnScroll' | 'closeOnClick' | 'interactive'> &
    Partial<Pick<TooltipProps, 'positioning'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        tooltip: TooltipHydrationProps;
    }
}
