// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as FileUploadProps } from '@zag-js/file-upload';

export type FileUploadHydrationProps = { id: string; ids: Record<string, string> } & Pick<
    FileUploadProps,
    'allowDrop' | 'maxFiles' | 'preventDocumentDrop' | 'directory' | 'translations'
> &
    Partial<
        Pick<
            FileUploadProps,
            | 'name'
            | 'disabled'
            | 'invalid'
            | 'required'
            | 'readOnly'
            | 'accept'
            | 'maxFileSize'
            | 'minFileSize'
            | 'capture'
        >
    > & { existingFilesCount: number };

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        fileUpload: FileUploadHydrationProps;
    }
}
