// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as ClipboardProps } from '@zag-js/clipboard';

export type ClipboardHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<ClipboardProps, 'value' | 'timeout' | 'translations'>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        clipboard: ClipboardHydrationProps;
    }
}
