// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as NumberInputProps } from '@zag-js/number-input';

export type NumberInputHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<NumberInputProps, 'defaultValue' | 'allowOverflow' | 'clampValueOnBlur' | 'focusInputOnChange' | 'spinOnPress' | 'inputMode' | 'pattern' | 'translations' | 'locale'> &
    Partial<Pick<NumberInputProps, 'disabled' | 'invalid' | 'required' | 'readOnly' | 'name' | 'form' | 'min' | 'max' | 'step' | 'smallStep' | 'largeStep' | 'allowMouseWheel' | 'formatOptions'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        numberInput: NumberInputHydrationProps;
    }
}
