// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as DialogProps } from '@zag-js/dialog';

export type DialogHydrationProps = { id: string; ids: Record<string, string> } & Pick<
    DialogProps,
    | 'trapFocus'
    | 'preventScroll'
    | 'modal'
    | 'restoreFocus'
    | 'closeOnInteractOutside'
    | 'closeOnEscape'
    | 'role'
    | 'defaultOpen'
>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        dialog: DialogHydrationProps;
    }
}
