// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { FormProps } from './src/form.types';

export type FormHydrationProps = { id: string; ids: Record<string, string> } & Partial<
    Pick<FormProps, 'objectName'>
>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        form: FormHydrationProps;
    }
}
