<?php

declare(strict_types=1);

namespace Jramke\FluidPrimitives\Tests\Unit;

use Jramke\FluidPrimitives\Tests\TestCase;
use Jramke\FluidPrimitives\Utility\ComponentUtility;
use PHPUnit\Framework\Attributes\Test;

final class ComponentUtilityTest extends TestCase
{
    #[Test]
    public function generatesUniqueIdsWithPrefix(): void
    {
        $id1 = ComponentUtility::id();
        $id2 = ComponentUtility::id();
        $id3 = ComponentUtility::id('custom');

        $this->assertStringStartsWith('«f', $id1);
        $this->assertStringEndsWith('»', $id1);
        $this->assertStringStartsWith('«custom', $id3);
        $this->assertNotSame($id1, $id2);
    }

    #[Test]
    public function generatesDifferentIdsAcrossSeparatePhpProcesses(): void
    {
        // Regression test: ComponentUtility::id() used to be a plain
        // per-process counter starting at 0 on every call. That is fine for
        // a single, full page render, but Jramke\FluidPrimitives\Service\ComponentFragmentRenderer
        // renders components in isolation from separate requests (e.g. a
        // lazily-fetched recurring-field row) - each of which is its own PHP
        // process/request lifecycle. Without a per-process random salt, two
        // separate fragment renders producing the exact same component
        // structure would always generate identical ids, silently colliding
        // in the client-side hydration data once merged onto the same page.
        // The autoloader lives in packages/fluid-primitives/vendor when this
        // package runs standalone (e.g. after being released), or in the
        // monorepo root's vendor when run as part of this repo.
        $candidatePaths = [
            dirname(__DIR__, 2) . '/vendor/autoload.php',
            dirname(__DIR__, 4) . '/vendor/autoload.php',
        ];
        $autoloadPath = null;
        foreach ($candidatePaths as $candidatePath) {
            if (!file_exists($candidatePath)) {
                continue;
            }

            $autoloadPath = $candidatePath;
            break;
        }
        $this->assertNotNull(
            $autoloadPath,
            'Expected a composer autoloader to exist for this standalone-process check.',
        );

        $script = sprintf('require %s; echo \Jramke\FluidPrimitives\Utility\ComponentUtility::id();', var_export(
            $autoloadPath,
            true,
        ));

        $id1 = shell_exec(sprintf('php -r %s', escapeshellarg($script)));
        $id2 = shell_exec(sprintf('php -r %s', escapeshellarg($script)));

        $this->assertNotSame($id1, $id2, 'Expected ids generated by separate PHP processes to differ.');
    }

    #[Test]
    public function handlesComplexNamesWithMultipleCapitals(): void
    {
        $result = ComponentUtility::getComponentFullNameFromViewHelperName('ScrollArea.Root');
        $this->assertSame('scroll-area.root', $result);
    }

    #[Test]
    public function skipsPrimitivesNamespace(): void
    {
        $result = ComponentUtility::getComponentBaseNameFromViewHelperName('Primitives.Dialog.Root');
        $this->assertSame('dialog', $result);
    }

    #[Test]
    public function extractsBaseNameFromCompoundComponent(): void
    {
        $result = ComponentUtility::getComponentBaseNameFromViewHelperName('Accordion.Item');
        $this->assertSame('accordion', $result);
    }

    #[Test]
    public function returnsFullSubcomponentPathForDeepNames(): void
    {
        $result = ComponentUtility::getSubcomponentNameFromViewHelperName('Accordion.Item.Trigger');
        $this->assertSame('item.trigger', $result);
    }

    #[Test]
    public function returnsTrueForSinglePartComponentName(): void
    {
        $this->assertTrue(ComponentUtility::isRootComponent('Collapsible'));
    }

    #[Test]
    public function returnsTrueWhenSecondPartIsRoot(): void
    {
        $this->assertTrue(ComponentUtility::isRootComponent('Accordion.Root'));
    }

    #[Test]
    public function returnsFalseForItemComponents(): void
    {
        $this->assertFalse(ComponentUtility::isRootComponent('Accordion.Item'));
    }

    #[Test]
    public function handlesPrimitivesNamespaceSecondPartIsNotRoot(): void
    {
        $this->assertFalse(ComponentUtility::isRootComponent('Primitives.Dialog.Root'));
    }
}
