// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { TextareaProps } from './src/textarea.types';

export type TextareaHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<TextareaProps, 'defaultValue' | 'translations' | 'announceDebounce'> &
    Partial<Pick<TextareaProps, 'name' | 'disabled' | 'invalid' | 'required' | 'readOnly' | 'maxLength' | 'submitOn'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        textarea: TextareaHydrationProps;
    }
}
