// AUTO-GENERATED by `ui:generate-hydration-types` - do not edit by hand.
import type { Props as AccordionProps } from '@zag-js/accordion';

export type AccordionHydrationProps =
    { id: string; ids: Record<string, string> } &
    Pick<AccordionProps, 'multiple' | 'collapsible' | 'orientation'> &
    Partial<Pick<AccordionProps, 'defaultValue' | 'disabled'>>;

declare module 'fluid-primitives/client' {
    interface HydrationPropsRegistry {
        accordion: AccordionHydrationProps;
    }
}
